### ISSUE TITLE
Build Instructions slightly faulty

### ISSUE THREAD

**Issue by aditya95sriram** [ben-strasser/flow-cutter-pace20#1]
While running `build.sh` I got an error saying `src/include_all.cpp: No such file or directory`.

I found `src/include_all.cpp` is present in `flow_cutter_pace20.tgz`, so I was still able to build.

To save future users the hassle I suggest adding the file to the repo as well and not just as a part of the gz archive.

**Comment by ben-strasser** [comment]
Thanks for the feedback! It should be fixed.
